#!/usr/bin/env python
from struct import pack, unpack
from sys import argv
value = int(argv[1], 0)
byte_length = (value.bit_length() - 1) / 8 + 1
types = ['B', 'B', 'H', 'L', 'L', 'Q', 'Q', 'Q', 'Q']
packed = pack('<' + types[byte_length], value)
unpacked, = unpack('>' + types[byte_length], packed)
print hex(unpacked)
