#!/usr/bin/env python
from struct import pack, unpack
from sys import argv
for idx in range(1, len(argv)):
    value = int(argv[idx], 0)
    byte_length = int((value.bit_length() - 1) / 8 + 1)
    types = ['B', 'B', 'H', 'L', 'L', 'Q', 'Q', 'Q', 'Q']
    packed = pack('<' + types[byte_length], value)
    unpacked, = unpack('>' + types[byte_length], packed)
    print('0x%x' % unpacked)
