#!/usr/bin/env python
from sys import argv
for idx in range(1, len(argv)):
    value = int(argv[idx], 0)
    value = ~value
    byte_length = int((value.bit_length() - 1) / 8 + 1)
    mask = (1 << (byte_length * 8)) - 1
    value &= mask
    print('0x%x' % value)
